import { Email } from "@/components/webmailer/types";

export const emails: Email[] = [
  {
    id: 0,
    labelId: 1,
    from: "Mike James",
    from_email: "test@test.de",
    to: "Tim Cook",
    to_email: "tim@dosenmatrosen.de",
    subject: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    time: "11:15",
    date: new Date("2024-12-17T03:24:00"),
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    unread: true,
  },
  {
    id: 1,
    labelId: 1,
    from: "Emma Thompson",
    from_email: "test@test.de",
    to: "Tim Cook",
    to_email: "tim@dosenmatrosen.de",
    subject: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    time: "22:08",
    date: new Date("2024-12-16T03:24:00"),
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    unread: true,
  },
  {
    id: 2,
    labelId: 1,
    from: "Olivia Jefferson",
    from_email: "test@test.de",
    to: "Tim Cook",
    to_email: "tim@dosenmatrosen.de",
    subject: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    time: "19:12",
    date: new Date("2024-12-11T03:24:00"),
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    unread: true,
  },
  {
    id: 3,
    labelId: 1,
    from: "Mike Conley",
    from_email: "test@test.de",
    to: "Tim Cook",
    to_email: "tim@dosenmatrosen.de",
    subject: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    time: "18:35",
    date: new Date("2024-12-10T03:24:00"),
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    unread: true,
  },
  {
    id: 4,
    labelId: 2,
    from: "Emily Iverson",
    from_email: "test@test.de",
    to: "Tim Cook",
    to_email: "tim@dosenmatrosen.de",
    date: new Date("2024-12-09T03:24:00"),
    subject: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    time: "14:05",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    unread: true,
  },
  {
    id: 5,
    labelId: 3,
    from: "Michael Neal",
    from_email: "test@test.de",
    to: "Tim Cook",
    to_email: "tim@dosenmatrosen.de",
    subject: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    time: "14:05",
    date: new Date("2024-12-11T01:21:00"),
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    unread: true,
  },
  {
    id: 6,
    labelId: 3,
    from: "Michael Neal",
    from_email: "test@test.de",
    to: "Tim Cook",
    to_email: "tim@dosenmatrosen.de",
    subject: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    time: "14:05",
    date: new Date("2024-12-11T01:21:00"),
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    unread: true,
  },
  {
    id: 7,
    labelId: 3,
    from: "Michael Neal",
    from_email: "test@test.de",
    to: "Tim Cook",
    to_email: "tim@dosenmatrosen.de",
    subject: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    time: "14:05",
    date: new Date("2024-12-11T01:21:00"),
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    unread: true,
  },
  {
    id: 8,
    labelId: 3,
    from: "Michael Neal",
    from_email: "test@test.de",
    to: "Tim Cook",
    to_email: "tim@dosenmatrosen.de",
    subject: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    time: "14:05",
    date: new Date("2024-12-11T01:21:00"),
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    unread: true,
  },
  {
    id: 9,
    labelId: 3,
    from: "Michael Neal",
    from_email: "test@test.de",
    to: "Tim Cook",
    to_email: "tim@dosenmatrosen.de",
    subject: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    time: "14:05",
    date: new Date("2024-12-11T01:21:00"),
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    unread: false,
  },
];
